model Z:\home\pablo\university\08_programacion_no_lineal_y_computacion_40209043\proyectos_40209043\toTheMoon\ampl_version\1.1_TTM.mod;
data Z:\home\pablo\university\08_programacion_no_lineal_y_computacion_40209043\proyectos_40209043\toTheMoon\ampl_version\1.1_TTM.dat;

solve;

print "sx", ",", "sy";
print {i in NN}: s[1, i], ",", s[2, i];

print "Instante", ",", "Empuje total";
print {i in NN}: i, Th[1, i]^2 + Th[2, i]^2;
#display Th;
#display s;
